

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
/**
 *Tests our Pushback Tokenizer. Makes sure a method is not null
 * @author Alex Diviney
 * @version 2.1.0
 */
package adapter;

import org.junit.Test;
import static org.junit.Assert.*;

/**
 * Tests our Tokenizer
 */
public class AppTest {
    @Test public void appHasAGreeting() {
        Tokenizer classUnderTest = new Tokenizer();
        assertNotNull("app should print false", classUnderTest.hasMoreTokens() );
    }
}
