/*
 * This Java source file was generated by the Gradle 'init' task.
 */
/**
 *Tests our Pushback Tokenizer. Makes sure a method is not null
 * @author Alex Diviney
 * @version 2.1.0
 */
package edu.isu.cs.cs2263;


import org.junit.jupiter.api.Test;


public class AppTest {
    @Test public void appHasAGreeting() {

        Tokenizer classUnderTest = new Tokenizer();
        assertNotNull("app should print false", classUnderTest.hasMoreTokens() );
    }

    private void assertNotNull(String app_should_print_false, boolean hasMoreTokens) {

    }
}
