/*
 * This Java source file was generated by the Gradle 'init' task.
 */
/** App class that initializes our pushbackTokenizer tests.

 * @author Alex Diviney
 * @version 2.1.0
 */
package adapter;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
